[platformio]
default_envs = mega2560

src_dir = src
include_dir = include

[env]
platform = atmelavr
framework = arduino
build_flags = -std=gnu++11
lib_deps = 
	arduino-libraries/Servo@^1.2.2
	electroniccats/MPU6050@^1.4.4
	bxparks/AceSorting@^1.0.0
	gyverlibs/GyverTimers@^1.10
	thijse/ArduinoLog@^1.1.1

[env:mega2560]
board = megaatmega2560