[platformio]
src_dir = src
include_dir = include

[env]
platform = atmelavr
framework = arduino
lib_deps =
	feilipu/FreeRTOS
	arduino-libraries/Servo@^1.2.2
	electroniccats/MPU6050@^1.4.4
	bxparks/AceSorting@^1.0.0
	thijse/ArduinoLog@^1.1.1
	bblanchon/ArduinoJson@^7.4.2
	mishamyrt/io_di@^1.0.0
build_flags =
	-DportUSE_WDTO=WDTO_15MS

[env:mega2560_enable_lift]
board = megaatmega2560
build_flags =
	${env.build_flags}
	-DGLOBAL_CONFIG__ENABLE_LIFT

[env:mega2560_disable_lift]
board = megaatmega2560
build_flags =
	${env.build_flags}
	-UGLOBAL_CONFIG__ENABLE_LIFT
