[platformio]
default_envs = mega2560

src_dir = src
include_dir = include


# src_dir = test/mpu/src
# include_dir = test/mpu/include

[env]
platform = atmelavr
framework = arduino
lib_deps =
	feilipu/FreeRTOS
	arduino-libraries/Servo@^1.2.2
	electroniccats/MPU6050@^1.4.4
	bxparks/AceSorting@^1.0.0
	thijse/ArduinoLog@^1.1.1
build_flags =
	-DportUSE_WDTO=WDTO_15MS

[env:mega2560]
board = megaatmega2560