#pragma once

// #define GLOBAL_CONFIG_MODE_AUTO
// #define GLOBAL_CONFIG_MODE_MANUALLY
#define GLOBAL_CONFIG_MODE_SUPERTEAM

#ifdef GLOBAL_CONFIG_MODE_AUTO
    #define GLOBAL_CONFIG_ENABLE_LIFT
#endif

#ifdef GLOBAL_CONFIG_MODE_AUTO
    #define MAX_SPEED 60
    #define GLOBAL_CONFIG_ENABLE_LIFT
#elif defined(GLOBAL_CONFIG_MODE_MANUALLY)
    #define MAX_SPEED 100
    #define GLOBAL_CONFIG_ENABLE_MANUALLY
#else // SUPERTEAM
    #define MAX_SPEED 60
#endif
